version: "3"

services:
  realsense-ros-jazzy:
    image: realsense-ros2-jazzy:latest
    container_name: realsense-ros2-jazzy
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    devices:
      - "/dev:/dev"
    network_mode: host
    privileged: true
    env_file:
      - .env
    command: 'bash -c "source /opt/ros/jazzy/setup.bash && ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30 rgb_camera.profile:=640x480x30"'

# You can remove depth_module.profile:=640x480x30 rgb_camera.profile:=640x480x30 from the command if you want to use the default profiles.
